### ISSUE TITLE
[v4] Failed to load plugin commitlint-plugin-function-rules

### ISSUE THREAD

**Issue by screendriver** [wagoid/commitlint-github-action#196]
Since the latest v4 release [I'm getting](https://github.com/screendriver/gitlab-pipeline-deleter/pull/74/checks?check_run_id=3074883492)

```
Failed to load plugin commitlint-plugin-function-rules.
Error: error running commitlint
Failed to load plugin commitlint-plugin-function-rules: Cannot find module 'commitlint-plugin-function-rules'
Require stack:
- /node_modules/@commitlint/load/lib/utils/load-plugin.js
- /node_modules/@commitlint/load/lib/load.js
Error: Failed to load plugin commitlint-plugin-function-rules: Cannot find module 'commitlint-plugin-function-rules'
Require stack:
- /node_modules/@commitlint/load/lib/utils/load-plugin.js
- /node_modules/@commitlint/load/lib/load.js
    at Object.loadPlugin [as default] (/node_modules/@commitlint/load/lib/utils/load-plugin.js:32:23)
    at /node_modules/@commitlint/load/lib/load.js:67:38
    at Array.forEach (<anonymous>)
    at load (/node_modules/@commitlint/load/lib/load.js:65:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async showLintResults (file:///src/action.js:132:7)

```

**Comment by wagoid** [comment]
Interesting, I wasn't officially supporting `commitlint-plugin-function-rules`. I had it only in `devDependencies`, probably there was a package in the `dependencies` field that depended on this plugin but stopped after an upgrade.

I'll add a PR officially supporting the plugin 👍
