### ISSUE TITLE
Found invalid rule names: subject-exclamation-mark

### ISSUE THREAD

**Issue by stefan-prokop-cz** [wagoid/commitlint-github-action#199]
After I upgraded `@commitlint/config-angular` (https://www.npmjs.com/package/@commitlint/config-angular) package from version `^12.1.4` to `^13.1.0`.

I received this error from the GH action (I am using `wagoid/commitlint-github-action@v4.1.1`):

```
error running commitlint
Found invalid rule names: subject-exclamation-mark. Supported rule names are: body-case, body-empty, body-full-stop, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, type-case, type-empty, type-enum, type-max-length, type-min-length
RangeError: Found invalid rule names: subject-exclamation-mark. Supported rule names are: body-case, body-empty, body-full-stop, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, type-case, type-empty, type-enum, type-max-length, type-min-length
    at Object.lint [as default] (/node_modules/@commitlint/lint/lib/lint.js:53:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /run.js:300:17
    at async Promise.all (index 0)
    at async showLintResults (/run.js:299:25)
```

It's something that was added here https://github.com/conventional-changelog/commitlint/commit/be701bdb1de4e667b7a872767244285c4fa4fda4 (changelog: https://github.com/conventional-changelog/commitlint/blob/master/CHANGELOG.md#features-1).

My commitlint config is just this:

```
module.exports = {
  extends: ['@commitlint/config-angular'],
  helpUrl: 'https://gist.github.com/brianclements/841ea7bffdb01346392c'
}
```

**Comment by wagoid** [comment]
Hey @stefan-prokop-cz! I've just upgraded `@commitlint/config-angular` to 13.1.0. It should work on `wagoid/commitlint-github-action@v4.1.4`.
Let me know if it still fails after the upgrade💪

**Comment by stefan-prokop-cz** [comment]
It works! Thanks :tada:
