### ISSUE TITLE
Bad credentials error

### ISSUE THREAD

**Issue by aminya** [wagoid/commitlint-github-action#40]
When I try to run commit lint I get this error.

```ps1
Run wagoid/commitlint-github-action@v1
/usr/bin/docker run --name wagoidcommitlintgithubaction170_f192fe --label 87c201 --workdir /github/workspace --rm -e INPUT_CONFIGFILE -e INPUT_FIRSTPARENT -e INPUT_FAILONWARNINGS -e INPUT_HELPURL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/atom-ide-template-js/atom-ide-template-js":"/github/workspace" wagoid/commitlint-github-action:1.7.0
##[error]error trying to get list of pull request's commits
Bad credentials
HttpError: Bad credentials
    at /node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getRangeForEvent (/action.js:51:29)
##[error]error running commitlint
undefined is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at showLintResults (/action.js:136:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
https://github.com/atom-ide-community/atom-ide-template-js/pull/22/checks?check_run_id=888622305

```yaml
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commit lint ✨
        uses: wagoid/commitlint-github-action@v1

```

Ref. https://github.com/atom-ide-community/atom-ide-template-js/pull/22

**Comment by wagoid** [comment]
Hi @aminya! This is probably because the `GITHUB_TOKEN` env var is not defined.

Could you try adding the following to the `lint` job?

```yaml
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

If you prefer, you can also add this env var to the `Commit Lint` step of the workflow file instead.

**Comment by wagoid** [comment]
Hey @aminya, I'm closing the issue. If you have further issues let me know :muscle:
