### ISSUE TITLE
Proxy error during container run

### ISSUE THREAD

**Issue by develloup** [wagoid/commitlint-github-action#686]
My environment is behind a proxy and all the environment are well copied to the container. Unfortunately the proxy refuses to connect because the network between container and host are different. I found a solution to add "--network host" to this call and the problem was healed. For that I wrote a docker wrapper, placed it at /usr/bin/docker, analyzed the parameter list, added the missing "--network host" and called the real docker executable. After that problem was gone.

My wish would be to have the possibility to extend the call to the docker to place individual parameters there. Would be great to have.

Run wagoid/commitlint-github-action@v5
/usr/bin/docker run --name wagoidcommitlintgithubaction531_4969f6 --label b9117c --workdir /github/workspace --rm -e "HTTP_PROXY" -e "http_proxy" -e "HTTPS_PROXY" -e "https_proxy" -e "NO_PROXY" -e "no_proxy" -e "INPUT_FAILONWARNINGS" -e "INPUT_COMMITDEPTH" -e "INPUT_CONFIGFILE" -e "INPUT_FIRSTPARENT" -e "INPUT_HELPURL" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/user/actions-runner/_work/_temp/_github_home":"/github/home" -v "/home/user/actions-runner/_work/_temp/_github_workflow":"/github/workflow" -v "/local/home/user/actions-runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/local/home/user/actions-runner/_work/...":"/github/workspace" wagoid/commitlint-github-action:5.3.1
Error: You have commit messages with errors

error trying to get list of pull request's commits
request to https://github.....com/api/v3/.../pulls/17/commits failed, reason: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:3128
HttpError: request to https://github.....com/api/v3/repos/..../pulls/17/commits failed, reason: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:3128
    at /node_modules/@octokit/request/dist-node/index.js:108:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getRangeForEvent (/run.js:234:7)
Error: You have commit messages with errors

error running commitlint
undefined is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at showLintResults (/run.js:300:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by gdvalderrama** [comment]
My organization just set up an enterprise and this started happening too

**Comment by wagoid** [comment]
Hey all! Sorry for the delay answering this issue.
Unfortunately, I don't think this is possible within Github Actions. The [documentation](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-container-actions) doesn't seem to have any way of passing extra parameters to the `docker run` command.

@develloup would it be possible for you to provide instructions on the way you fixed this issue? I'd be happy to include it in the readme

**Comment by develloup** [comment]
Oh, sorry, I was not looking into this for a long time. Therefore just my 2 cents how I solved this problem on my buildserver. The prerequisite for this is that you have admin rights.

So, I created a small python script which is a wrapper for docker. I'm scanning the command line for certain keywords, like build, run (the docker commands) and e.g. wagoid. Then I'm adding the "--network=host" into this commandline and then I call the true docker executable.

Steps to install this solution is to go to /usr/bin. Rename the docker to e.g. dockerint. Then install the python script as docker, give it executable rights and then scan the command lines and forward the call to docker after extending the parameters. Here you go.


/usr/bin/docker run --name wagoidcommitlintgithubaction543_0b70f5 --label b9117c --workdir /github/workspace --rm -e "HTTP_PROXY" -e "http_proxy" -e "HTTPS_PROXY" -e "https_proxy" -e "NO_PROXY" -e "no_proxy" -e "INPUT_FAILONWARNINGS" -e "INPUT_COMMITDEPTH" -e "INPUT_CONFIGFILE" -e "INPUT_FAILONERRORS" -e "INPUT_HELPURL" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/local/home/rbadmin_app1/actions-runner/_work/_temp/_github_home":"/github/home" -v "/local/home/rbadmin_app1/actions-runner/_work/_temp/_github_workflow":"/github/workflow" -v "/local/home/rbadmin_app1/actions-runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/local/home/rbadmin_app1/actions-runner/_work/sdv-edge-ref-distro/sdv-edge-ref-distro":"/github/workspace" wagoid/commitlint-github-action:5.4.3
Lint free! 🎉
['**/usr/bin/dockerint**', 'run', '--name', 'wagoidcommitlintgithubaction543_0b70f5', '--label', 'b9117c', '--workdir', '/github/workspace', '--rm', '-e', 'HTTP_PROXY', '-e', 'http_proxy', '-e', 'HTTPS_PROXY', '-e', 'https_proxy', '-e', 'NO_PROXY', '-e', 'no_proxy', '-e', 'INPUT_FAILONWARNINGS', '-e', 'INPUT_COMMITDEPTH', '-e', 'INPUT_CONFIGFILE', '-e', 'INPUT_FAILONERRORS', '-e', 'INPUT_HELPURL', '-e', 'INPUT_TOKEN', '-e', 'HOME', '-e', 'GITHUB_JOB', '-e', 'GITHUB_REF', '-e', 'GITHUB_SHA', '-e', 'GITHUB_REPOSITORY', '-e', 'GITHUB_REPOSITORY_OWNER', '-e', 'GITHUB_RUN_ID', '-e', 'GITHUB_RUN_NUMBER', '-e', 'GITHUB_RETENTION_DAYS', '-e', 'GITHUB_RUN_ATTEMPT', '-e', 'GITHUB_ACTOR', '-e', 'GITHUB_TRIGGERING_ACTOR', '-e', 'GITHUB_WORKFLOW', '-e', 'GITHUB_HEAD_REF', '-e', 'GITHUB_BASE_REF', '-e', 'GITHUB_EVENT_NAME', '-e', 'GITHUB_SERVER_URL', '-e', 'GITHUB_API_URL', '-e', 'GITHUB_GRAPHQL_URL', '-e', 'GITHUB_REF_NAME', '-e', 'GITHUB_REF_PROTECTED', '-e', 'GITHUB_REF_TYPE', '-e', 'GITHUB_WORKSPACE', '-e', 'GITHUB_ACTION', '-e', 'GITHUB_EVENT_PATH', '-e', 'GITHUB_ACTION_REPOSITORY', '-e', 'GITHUB_ACTION_REF', '-e', 'GITHUB_PATH', '-e', 'GITHUB_ENV', '-e', 'GITHUB_STEP_SUMMARY', '-e', 'GITHUB_STATE', '-e', 'GITHUB_OUTPUT', '-e', 'RUNNER_OS', '-e', 'RUNNER_ARCH', '-e', 'RUNNER_NAME', '-e', 'RUNNER_TOOL_CACHE', '-e', 'RUNNER_TEMP', '-e', 'RUNNER_WORKSPACE', '-e', 'ACTIONS_RUNTIME_URL', '-e', 'ACTIONS_RUNTIME_TOKEN', '-e', 'ACTIONS_CACHE_URL', '-e', 'GITHUB_ACTIONS=true', '-e', 'CI=true', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-v', '/local/home/rbadmin_app1/actions-runner/_work/_temp/_github_home:/github/home', '-v', '/local/home/rbadmin_app1/actions-runner/_work/_temp/_github_workflow:/github/workflow', '-v', '/local/home/rbadmin_app1/actions-runner/_work/_temp/_runner_file_commands:/github/file_commands', '-v', '/local/home/rbadmin_app1/actions-runner/_work/sdv-edge-ref-distro/sdv-edge-ref-distro:/github/workspace', 'wagoid/commitlint-github-action:5.4.3', **'--network=host'**]

**Comment by develloup** [comment]
Oh, and I forgot, if you have problems with generating a docker image with docker build, then it was also a help for me to add: "--build-arg", "https_proxy=${https_proxy}", "--build-arg", "http_proxy=${http_proxy}" for certain github actions to the command line.

**Comment by wagoid** [comment]
That's great! Thanks for the explanation @develloup ❤️
