### ISSUE TITLE
error running commitlint: undefined is not iterable

### ISSUE THREAD

**Issue by shanduur** [wagoid/commitlint-github-action#742]
Encountered the following issue today:

```
error trying to get list of pull request's commits
Resource not accessible by integration
HttpError: Resource not accessible by integration
    at /node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getRangeForEvent (/run.js:234:7)
Error: You have commit messages with errors

error running commitlint
undefined is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at showLintResults (/run.js:300:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by totally-andre** [comment]
I was able to get rid of this error by adding permissions to the workflow yaml. The `wagoid/commitlint-github-action` uses [`octokit.rest.pulls.listCommits()`](https://octokit.github.io/rest.js/v19#pulls-list-commits) to fetch the commits for a pull request. As described in the [GitHub Developer Guide documentation](https://docs.github.com/rest/reference/pulls#list-commits-on-a-pull-request), this operation needs the permission to access the API endpoint `GET /repos/{owner}/{repo}/pulls/{pull_number}/commits`. As you can read at [Permissions required for GitHub Apps](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#repository-permissions-for-pull-requests) this endpoint requires the `PullRequests: read` permission as well as the repository permission for `Contents`. So, adding the following to the workflow yaml file solves this issue:
```yaml
permissions:
  contents: read
  pull-requests: read
```
