### ISSUE TITLE
Error: module is not defined in ES module scope

### ISSUE THREAD

**Issue by cgrinds** [wagoid/commitlint-github-action#777]
https://github.com/NetApp/harvest/blob/main/.github/workflows/commitlint.yml
uses `wagoid/commitlint-github-action@v6` like so:

```yaml
name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
```

When running, the following [error](https://github.com/NetApp/harvest/actions/runs/8520589178/job/23337020441?pr=2799) happens

```
2024-04-02T09:33:16.3241354Z ##[group]Run wagoid/commitlint-github-action@v6.0.0
2024-04-02T09:33:16.3241912Z with:
2024-04-02T09:33:16.3242216Z   configFile: ./commitlint.config.mjs
2024-04-02T09:33:16.3242780Z   failOnWarnings: false
2024-04-02T09:33:16.3243140Z   failOnErrors: true
2024-04-02T09:33:16.3243669Z   helpURL: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
2024-04-02T09:33:16.3244558Z   token: ***
2024-04-02T09:33:16.3244879Z ##[endgroup]
2024-04-02T09:33:16.3449703Z ##[command]/usr/bin/docker run --name wagoidcommitlintgithubaction600_0b34fb --label 0d66b2 --workdir /github/workspace --rm -e "INPUT_CONFIGFILE" -e "INPUT_FAILONWARNINGS" -e "INPUT_FAILONERRORS" -e "INPUT_HELPURL" -e "INPUT_COMMITDEPTH" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/harvest/harvest":"/github/workspace" wagoid/commitlint-github-action:6.0.0
2024-04-02T09:33:17.3672705Z ##[error]You have commit messages with errors

error running commitlint
module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///github/workspace/commitlint.config.js:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
    at async loadJs (/node_modules/@commitlint/load/node_modules/cosmiconfig/dist/loaders.js:23:17)
    at async #loadConfiguration (/node_modules/@commitlint/load/node_modules/cosmiconfig/dist/Explorer.js:116:36)
    at async #loadConfigFileWithImports (/node_modules/@commitlint/load/node_modules/cosmiconfig/dist/Explorer.js:87:31)
    at async #readConfiguration (/node_modules/@commitlint/load/node_modules/cosmiconfig/dist/Explorer.js:84:51)
    at async search (/node_modules/@commitlint/load/node_modules/cosmiconfig/dist/Explorer.js:50:40)
    at async Explorer.search (/node_modules/@commitlint/load/node_modules/cosmiconfig/dist/Explorer.js:78:20)
2024-04-02T09:33:17.5604745Z Post job cleanup.
```

**Comment by wagoid** [comment]
In v6, the config file must have the `.mjs` extension instead of `.js`. See https://github.com/wagoid/commitlint-github-action?tab=readme-ov-file#configfile

**Comment by cgrinds** [comment]
Thanks! For anyone else stumbling across this issue, I renamed `commitlint.config.js` to `commitlint.config.mjs` and then changed the exports line in `commitlint.config.mjs` from `module.exports = {` to `export default {`.

After making those changes, commitlint worked again.
